"""Initial Migrate

Revision ID: d95ec713d736
Revises: 
Create Date: 2022-11-26 07:06:33.364378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95ec713d736'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('cliente_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('sobrenome', sa.String(length=64), nullable=False),
    sa.Column('cpf', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('telefone', sa.String(length=80), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cliente_id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('sobrenome', sa.String(length=64), nullable=False),
    sa.Column('cpf', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('telefone', sa.String(length=80), nullable=False),
    sa.Column('administrador', sa.String(length=3), nullable=False),
    sa.Column('senha', sa.VARCHAR(length=164), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('servicos',
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('servico', sa.String(length=64), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('tempo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('servico_id'),
    sa.UniqueConstraint('servico')
    )
    op.create_table('agendamentos',
    sa.Column('agendamento_id', sa.Integer(), nullable=False),
    sa.Column('agendamento_data', sa.DateTime(), nullable=False),
    sa.Column('agendamento_data_fim', sa.DateTime(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.cliente_id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['id'], ['funcionarios.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.servico_id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('agendamento_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agendamentos')
    op.drop_table('servicos')
    op.drop_table('funcionarios')
    op.drop_table('clientes')
    # ### end Alembic commands ###
